# from https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows#example-caller-workflow
name: Call a reusable workflow

#on:
  #pull_request:
    #branches:
      #- main
on: [push]
#on:
  #push:
    #branches: [ "main", "master" ]

jobs:
  #call-workflow:
    #uses: octo-org/example-repo/.github/workflows/workflow-A.yml@v1

  call-workflow:
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    #uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    uses: laur89/workflows/.github/workflows/build-publish.yml@master
    #with:
      #config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  # need to explicitly define pypi release step, as publish to pypi cannot be ran
  # from reusable workflows, follow
  # https://github.com/pypa/gh-action-pypi-publish/issues/166 for more details
  publish-to-pypi:
    name: >-
      Publish Python ğŸ distribution ğŸ“¦ to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - call-workflow
    runs-on: ubuntu-latest
    environment:
      name: pypi
      #url: https://pypi.org/p/<package-name>  # Replace <package-name> with your PyPI project name; optional
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: release-dist
        path: dist/
    - name: Publish distribution ğŸ“¦ to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
